window.ForgeFleetDefaults = {
  roles: [
    { id: "ROL-001", name: "Admin" },
    { id: "ROL-002", name: "Manager" },
    { id: "ROL-003", name: "Mechanic" },
    { id: "ROL-004", name: "Driver" },
  ],
  users: [
    {
      id: "USR-001",
      name: "Felix Dela Cruz",
      email: "admin@forgefleet.demo",
      password: "admin123",
      role: "admin",
      phone: "+63 917 555 0101",
      status: "Active",
    },
    {
      id: "USR-002",
      name: "Maria Santos",
      email: "manager@forgefleet.demo",
      password: "manager123",
      role: "manager",
      phone: "+63 917 555 0102",
      status: "Active",
    },
    {
      id: "USR-003",
      name: "Noel Ramos",
      email: "mechanic@forgefleet.demo",
      password: "mechanic123",
      role: "mechanic",
      phone: "+63 917 555 0103",
      status: "Active",
    },
    {
      id: "USR-004",
      name: "Carlo Reyes",
      email: "driver@forgefleet.demo",
      password: "driver123",
      role: "driver",
      phone: "+63 917 555 0104",
      status: "Active",
    },
    {
      id: "USR-005",
      name: "Liza Mendoza",
      email: "liza@forgefleet.demo",
      password: "demo123",
      role: "driver",
      phone: "+63 917 555 0105",
      status: "Inactive",
    },
  ],
  drivers: [
    {
      id: "DRV-001",
      userId: "USR-004",
      name: "Carlo Reyes",
      license: "N01-23-456789",
      phone: "+63 917 555 0104",
      status: "Assigned",
    },
    {
      id: "DRV-002",
      userId: "USR-005",
      name: "Liza Mendoza",
      license: "N02-24-112233",
      phone: "+63 917 555 0105",
      status: "Available",
    },
    {
      id: "DRV-003",
      name: "Samuel Ong",
      license: "N03-22-987654",
      phone: "+63 917 555 0106",
      status: "Available",
    },
  ],
  mechanics: [
    {
      id: "MEC-001",
      userId: "USR-003",
      name: "Noel Ramos",
      specialty: "Heavy vehicle systems",
      status: "Active",
    },
    {
      id: "MEC-002",
      name: "Ana Lim",
      specialty: "Electrical diagnostics",
      status: "Active",
    },
  ],
  vehicles: [
    {
      id: "VEH-001",
      plate: "FF 2048",
      model: "Axiom Hauler 48",
      manufacturer: "Forge Motors",
      year: 2024,
      type: "Class 8 Tractor",
      mileage: 184220,
      status: "Active",
      driverId: "DRV-001",
      health: 96,
    },
    {
      id: "VEH-002",
      plate: "FF 1182",
      model: "Vanta Cargo 12",
      manufacturer: "Vanta",
      year: 2022,
      type: "Box Truck",
      mileage: 92380,
      status: "Maintenance",
      driverId: null,
      health: 78,
    },
    {
      id: "VEH-003",
      plate: "FF 0631",
      model: "Forge Lift 31",
      manufacturer: "Forge Motors",
      year: 2023,
      type: "Service Van",
      mileage: 64120,
      status: "Inspection",
      driverId: null,
      health: 88,
    },
    {
      id: "VEH-004",
      plate: "FF 3990",
      model: "Obsidian Tanker 90",
      manufacturer: "Obsidian",
      year: 2021,
      type: "Fuel Tanker",
      mileage: 211040,
      status: "Out of Service",
      driverId: null,
      health: 62,
    },
  ],
  assignments: [
    {
      id: "ASN-001",
      vehicleId: "VEH-001",
      driverId: "DRV-001",
      startDate: "2026-01-15",
      endDate: null,
      status: "Active",
    },
    {
      id: "ASN-002",
      vehicleId: "VEH-002",
      driverId: "DRV-002",
      startDate: "2025-06-10",
      endDate: "2026-02-28",
      status: "Ended",
    },
  ],
  serviceTypes: [
    {
      id: "SVC-001",
      name: "Preventive Maintenance A",
      intervalKm: 10000,
      status: "Active",
    },
    {
      id: "SVC-002",
      name: "Brake System Inspection",
      intervalKm: 15000,
      status: "Active",
    },
    {
      id: "SVC-003",
      name: "Annual Safety Inspection",
      intervalKm: 0,
      status: "Active",
    },
  ],
  schedules: [
    {
      id: "SCH-001",
      vehicleId: "VEH-002",
      serviceTypeId: "SVC-001",
      dueDate: "2026-07-20",
      status: "Overdue",
    },
    {
      id: "SCH-002",
      vehicleId: "VEH-003",
      serviceTypeId: "SVC-003",
      dueDate: "2026-07-28",
      status: "Upcoming",
    },
    {
      id: "SCH-003",
      vehicleId: "VEH-001",
      serviceTypeId: "SVC-002",
      dueDate: "2026-08-09",
      status: "Upcoming",
    },
  ],
  maintenance: [
    {
      id: "MNT-001",
      vehicleId: "VEH-002",
      serviceTypeId: "SVC-001",
      mechanicId: "MEC-001",
      serviceDate: "2026-07-16",
      completionDate: null,
      status: "In Progress",
      cost: 680,
      findings: "Transmission fluid below service threshold.",
      workPerformed: "Initial inspection completed.",
      notes: "Awaiting filter kit.",
    },
    {
      id: "MNT-002",
      vehicleId: "VEH-001",
      serviceTypeId: "SVC-001",
      mechanicId: "MEC-002",
      serviceDate: "2026-06-28",
      completionDate: "2026-06-28",
      status: "Completed",
      cost: 1240,
      findings: "No exceptions.",
      workPerformed: "Oil, filter, and inspection package.",
      notes: "Returned to service.",
    },
    {
      id: "MNT-003",
      vehicleId: "VEH-004",
      serviceTypeId: "SVC-002",
      mechanicId: "MEC-001",
      serviceDate: "2026-07-18",
      completionDate: null,
      status: "Pending",
      cost: 0,
      findings: "",
      workPerformed: "",
      notes: "Priority diagnostic task.",
    },
  ],
  mileageLogs: [
    {
      id: "MLG-001",
      vehicleId: "VEH-001",
      driverId: "DRV-001",
      date: "2026-07-14",
      mileage: 184220,
      notes: "North-Central route",
    },
    {
      id: "MLG-002",
      vehicleId: "VEH-001",
      driverId: "DRV-001",
      date: "2026-07-12",
      mileage: 183734,
      notes: "Central-North return",
    },
    {
      id: "MLG-003",
      vehicleId: "VEH-002",
      driverId: "DRV-002",
      date: "2026-06-08",
      mileage: 92380,
      notes: "Final assigned trip",
    },
  ],
  notifications: [
    {
      id: "NTF-001",
      userId: "USR-003",
      role: "mechanic",
      type: "Maintenance",
      title: "Priority diagnostic assigned",
      message: "Brake pressure diagnostics for FF 3990 is assigned to you.",
      date: "2026-07-18T09:30:00",
      read: false,
    },
    {
      id: "NTF-002",
      userId: "USR-004",
      role: "driver",
      type: "Reminder",
      title: "Service window approaching",
      message: "FF 2048 brake inspection is due on August 9.",
      date: "2026-07-17T12:00:00",
      read: false,
    },
    {
      id: "NTF-003",
      userId: "USR-001",
      role: "admin",
      type: "System",
      title: "Monthly fleet snapshot ready",
      message: "The July demonstration report is available.",
      date: "2026-07-16T08:00:00",
      read: true,
    },
    {
      id: "NTF-004",
      role: "manager",
      type: "Schedule",
      title: "Overdue schedule",
      message: "FF 1182 preventive maintenance is overdue.",
      date: "2026-07-18T07:15:00",
      read: false,
    },
  ],
  auditLogs: [
    {
      id: "AUD-001",
      userId: "USR-001",
      action: "Updated vehicle status",
      entity: "VEH-002",
      date: "2026-07-17T14:20:00",
    },
    {
      id: "AUD-002",
      userId: "USR-002",
      action: "Created maintenance schedule",
      entity: "SCH-003",
      date: "2026-07-16T10:05:00",
    },
    {
      id: "AUD-003",
      userId: "USR-003",
      action: "Updated maintenance task",
      entity: "MNT-001",
      date: "2026-07-16T16:45:00",
    },
  ],
};
window.ForgeFleetDashboard = {
  currentUser: {
    name: "Fleet Director",
    subtitle: "Operations Lead",
    initials: "FD",
  },
  hero: {
    id: "VEH-2048",
    asset: "FF-2048",
    name: "Axiom Hauler",
    number: "48",
    type: "Class 8 Tractor",
    status: "Ready",
    health: 96,
    utilization: 91,
    mileage: 184220,
    driver: "M. Ellis",
    route: "North Yard to Central Hub",
    nextService: "PM-B service · Jul 26",
    openOrders: 2,
  },
  kpis: [
    {
      label: "Fleet Readiness",
      value: "94%",
      detail: "+3.2% this week",
      tone: "green",
      icon: "shield",
    },
    {
      label: "Active Vehicles",
      value: "128",
      detail: "11 in service",
      tone: "gold",
      icon: "truck",
    },
    {
      label: "Open Work Orders",
      value: "24",
      detail: "6 high priority",
      tone: "yellow",
      icon: "clipboard",
    },
    {
      label: "Monthly Spend",
      value: "$84.7K",
      detail: "-8.5% vs forecast",
      tone: "green",
      icon: "chart",
    },
  ],
  trend: {
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    readiness: [88, 90, 91, 88, 93, 94, 95],
    utilization: [76, 78, 82, 79, 86, 88, 92],
  },
  operations: [
    { label: "Available vehicles", value: 94, total: 128, tone: "green" },
    { label: "In service", value: 18, total: 128, tone: "gold" },
    { label: "Under maintenance", value: 10, total: 128, tone: "yellow" },
    { label: "Out of service", value: 6, total: 128, tone: "red" },
  ],
  reminders: [
    {
      id: "SRV-308",
      asset: "FF-3990",
      vehicle: "Obsidian Tanker 90",
      service: "Brake pressure diagnostics",
      due: "Overdue by 2 days",
      threshold: "211,000 mi",
      status: "Overdue",
    },
    {
      id: "SRV-309",
      asset: "FF-1182",
      vehicle: "Vanta Cargo 12",
      service: "Transmission fluid service",
      due: "Due in 3 days",
      threshold: "93,000 mi",
      status: "Due Soon",
    },
    {
      id: "SRV-310",
      asset: "FF-0631",
      vehicle: "Forge Lift 31",
      service: "Annual safety inspection",
      due: "Jul 28, 2026",
      threshold: "65,000 mi",
      status: "Scheduled",
    },
    {
      id: "SRV-311",
      asset: "FF-2048",
      vehicle: "Axiom Hauler 48",
      service: "PM-B service window",
      due: "Aug 9, 2026",
      threshold: "190,000 mi",
      status: "Scheduled",
    },
  ],
  activity: [
    {
      id: "ACT-401",
      asset: "FF-2048",
      action: "PM-A inspection completed",
      mechanic: "Ana Lim",
      time: "18 min ago",
      cost: "$1,240",
      status: "Completed",
    },
    {
      id: "ACT-402",
      asset: "FF-1182",
      action: "Transmission service started",
      mechanic: "Noel Ramos",
      time: "41 min ago",
      cost: "$680 est.",
      status: "In Progress",
    },
    {
      id: "ACT-403",
      asset: "FF-0631",
      action: "ADAS calibration reviewed",
      mechanic: "Ana Lim",
      time: "1 hr ago",
      cost: "$740",
      status: "Completed",
    },
    {
      id: "ACT-404",
      asset: "FF-3990",
      action: "Brake diagnostics escalated",
      mechanic: "Noel Ramos",
      time: "2 hrs ago",
      cost: "Pending",
      status: "Priority",
    },
  ],
  notifications: [
    {
      id: "NTF-011",
      title: "3 overdue maintenance services",
      message: "Immediate scheduling attention is required.",
      time: "8 min ago",
      tone: "red",
    },
    {
      id: "NTF-012",
      title: "6 priority work orders",
      message: "Two work orders are awaiting assignment.",
      time: "32 min ago",
      tone: "yellow",
    },
    {
      id: "NTF-013",
      title: "FF-2048 returned to service",
      message: "PM-A inspection completed successfully.",
      time: "1 hr ago",
      tone: "green",
    },
  ],
  searchable: [
    {
      type: "Vehicle",
      id: "VEH-2048",
      title: "FF-2048 · Axiom Hauler 48",
      detail: "Ready · North Yard",
    },
    {
      type: "Vehicle",
      id: "VEH-1182",
      title: "FF-1182 · Vanta Cargo 12",
      detail: "In service · Central Hub",
    },
    {
      type: "Driver",
      id: "DRV-102",
      title: "M. Ellis",
      detail: "Assigned to FF-2048",
    },
    { type: "Driver", id: "DRV-117", title: "A. Novak", detail: "Central Hub" },
    {
      type: "Work order",
      id: "WO-2406",
      title: "Brake pressure diagnostics",
      detail: "FF-3990 · Critical",
    },
    {
      type: "Work order",
      id: "WO-2411",
      title: "Transmission fluid service",
      detail: "FF-1182 · In progress",
    },
  ],
};
